spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      mode: always

mybatis-plus:
  global-config:
    db-config:
      capital-mode: true

logging:
  level:
    com.baomidou.samples: debug